#### apple Data 만들기

In [2]:
import pandas as pd
import numpy as np

In [3]:
apple_length = [25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0, 31.5, 32.0, 32.0, 32.0, 33.0, 33.0, 33.5, 33.5, 34.0, 34.0, 34.5, 35.0, 35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0]
apple_weight = [242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0, 500.0, 340.0, 600.0, 600.0, 700.0, 700.0, 610.0, 650.0, 575.0, 685.0, 620.0, 680.0, 700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0]

apple = pd.DataFrame(
  {
    'length' : apple_length,
    'weight' : apple_weight,
    'name' : "apple"
  }
)

apple.head()

   length  weight   name
0    25.4   242.0  apple
1    26.3   290.0  apple
2    26.5   340.0  apple
3    29.0   363.0  apple
4    29.0   430.0  apple

In [4]:
apple.shape

(35, 3)

In [5]:
apple.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   length  35 non-null     float64
 1   weight  35 non-null     float64
 2   name    35 non-null     object
dtypes: float64(2), object(1)
memory usage: 972.0+ bytes

### berry Data 만들기

In [6]:
berry_length = [9.8, 10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]
berry_weight = [6.7, 7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]

berry = pd.DataFrame(
  {
    'length' : berry_length,
    'weight' : berry_weight,
    'name' : "berry"
  }
)

berry.head()

   length  weight   name
0     9.8     6.7  berry
1    10.5     7.5  berry
2    10.6     7.0  berry
3    11.0     9.7  berry
4    11.2     9.8  berry

In [7]:
berry.shape

(14, 3)

In [8]:
berry.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   length  14 non-null     float64
 1   weight  14 non-null     float64
 2   name    14 non-null     object
dtypes: float64(2), object(1)
memory usage: 468.0+ bytes

In [13]:
# Data 합치기
fruits = \
pd.concat(
  [apple, berry],
  ignore_index=True,
  axis=0,
)
fruits.tail()

    length  weight   name
44    12.2    12.2  berry
45    12.4    13.4  berry
46    13.0    12.2  berry
47    14.3    19.7  berry
48    15.0    19.9  berry

In [ ]:
# 저장하기 : ../Data/fruits.csv

fruits.to_csv("../Data/fruits.csv", index=False)