In [6]:
# Module
from bs4 import BeautifulSoup
from selenium import webdriver
import urllib.request as req
import os
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By

In [7]:
def scroll_down(driver, pause_time=1.5):
    prev_height = driver.execute_script("return document.body.scrollHeight")
    while True:
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(pause_time)
        curr_height = driver.execute_script("return document.body.scrollHeight")
        if curr_height == prev_height:
            break
        prev_height = curr_height

In [21]:
# 실행
driver = webdriver.Chrome()
driver.get("https://my.homeplus.co.kr/store")

In [ ]:



# 버튼 클릭
xpath = '//*[@id="btnSearchStoreH"]'
element = driver.find_element(By.XPATH, xpath)
actions = ActionChains(driver)
actions.move_to_element(element).perform()
time.sleep(0.5)
element.click()

# 스크롤 충분히 내리기
time.sleep(2)
scroll_down(driver, pause_time=1.5)

# 전체 페이지 파싱
html = driver.page_source
soup = BeautifulSoup(html,"html.parser")
b_list = soup.select("body > div > section > div.search-store__cont > div.searchResult > ul > li >div > a")

# 결과 추출
links = []
for b in b_list:
    link = "https://my.homeplus.co.kr/"+b.attrs['href']
    links.append(link)
    print(link)
    a = b.find("span")
    print(a.text.strip())

driver.quit()

https://my.homeplus.co.kr//store/store_detail?storId=590
0
https://my.homeplus.co.kr//store/store_detail?storId=591
0
https://my.homeplus.co.kr//store/store_detail?storId=592
0
https://my.homeplus.co.kr//store/store_detail?storId=593
0
https://my.homeplus.co.kr//store/store_detail?storId=594
0
https://my.homeplus.co.kr//store/store_detail?storId=595
0
https://my.homeplus.co.kr//store/store_detail?storId=596
0
https://my.homeplus.co.kr//store/store_detail?storId=597
0
https://my.homeplus.co.kr//store/store_detail?storId=649
0
https://my.homeplus.co.kr//store/store_detail?storId=598
0
https://my.homeplus.co.kr//store/store_detail?storId=599
0
https://my.homeplus.co.kr//store/store_detail?storId=601
0
https://my.homeplus.co.kr//store/store_detail?storId=639
0
https://my.homeplus.co.kr//store/store_detail?storId=602
0
https://my.homeplus.co.kr//store/store_detail?storId=603
0
https://my.homeplus.co.kr//store/store_detail?storId=604
0
https://my.homeplus.co.kr//store/store_detail?storId=605
0
https://my.homeplus.co.kr//store/store_detail?storId=606
0
https://my.homeplus.co.kr//store/store_detail?storId=607
0
https://my.homeplus.co.kr//store/store_detail?storId=608
0
https://my.homeplus.co.kr//store/store_detail?storId=609
0
https://my.homeplus.co.kr//store/store_detail?storId=610
0
https://my.homeplus.co.kr//store/store_detail?storId=611
0
https://my.homeplus.co.kr//store/store_detail?storId=618
0
https://my.homeplus.co.kr//store/store_detail?storId=612
0
https://my.homeplus.co.kr//store/store_detail?storId=613
0
https://my.homeplus.co.kr//store/store_detail?storId=614
0
https://my.homeplus.co.kr//store/store_detail?storId=549
0
https://my.homeplus.co.kr//store/store_detail?storId=552
0
https://my.homeplus.co.kr//store/store_detail?storId=554
0
https://my.homeplus.co.kr//store/store_detail?storId=556
0
https://my.homeplus.co.kr//store/store_detail?storId=557
0
https://my.homeplus.co.kr//store/store_detail?storId=558
0
https://my.homeplus.co.kr//store/store_detail?storId=559
0
https://my.homeplus.co.kr//store/store_detail?storId=560
0
https://my.homeplus.co.kr//store/store_detail?storId=561
0
https://my.homeplus.co.kr//store/store_detail?storId=563
0
https://my.homeplus.co.kr//store/store_detail?storId=576
0
https://my.homeplus.co.kr//store/store_detail?storId=577
0
https://my.homeplus.co.kr//store/store_detail?storId=578
0
https://my.homeplus.co.kr//store/store_detail?storId=579
0
https://my.homeplus.co.kr//store/store_detail?storId=580
0
https://my.homeplus.co.kr//store/store_detail?storId=581
0
https://my.homeplus.co.kr//store/store_detail?storId=582
0
https://my.homeplus.co.kr//store/store_detail?storId=641
0
https://my.homeplus.co.kr//store/store_detail?storId=583
0
https://my.homeplus.co.kr//store/store_detail?storId=584
0
https://my.homeplus.co.kr//store/store_detail?storId=585
0
https://my.homeplus.co.kr//store/store_detail?storId=586
0
https://my.homeplus.co.kr//store/store_detail?storId=587
0
https://my.homeplus.co.kr//store/store_detail?storId=588
0
https://my.homeplus.co.kr//store/store_detail?storId=564
0
https://my.homeplus.co.kr//store/store_detail?storId=565
0
https://my.homeplus.co.kr//store/store_detail?storId=566
0
https://my.homeplus.co.kr//store/store_detail?storId=567
0
https://my.homeplus.co.kr//store/store_detail?storId=570
0
https://my.homeplus.co.kr//store/store_detail?storId=646
0
https://my.homeplus.co.kr//store/store_detail?storId=651
0
https://my.homeplus.co.kr//store/store_detail?storId=652
0
https://my.homeplus.co.kr//store/store_detail?storId=571
0
https://my.homeplus.co.kr//store/store_detail?storId=653
0
https://my.homeplus.co.kr//store/store_detail?storId=572
0
https://my.homeplus.co.kr//store/store_detail?storId=573
0
https://my.homeplus.co.kr//store/store_detail?storId=574
0
https://my.homeplus.co.kr//store/store_detail?storId=575
0
https://my.homeplus.co.kr//store/store_detail?storId=656
0
https://my.homeplus.co.kr//store/store_detail?storId=657
0
https://my.homeplus.co.kr//store/store_detail?storId=658
0
https://my.homeplus.co.kr//store/store_detail?storId=659
0
https://my.homeplus.co.kr//store/store_detail?storId=660
0
https://my.homeplus.co.kr//store/store_detail?storId=642
0
https://my.homeplus.co.kr//store/store_detail?storId=661
0
https://my.homeplus.co.kr//store/store_detail?storId=662
0
https://my.homeplus.co.kr//store/store_detail?storId=665
0
https://my.homeplus.co.kr//store/store_detail?storId=666
0
https://my.homeplus.co.kr//store/store_detail?storId=667
0
https://my.homeplus.co.kr//store/store_detail?storId=668
0
https://my.homeplus.co.kr//store/store_detail?storId=669
0
https://my.homeplus.co.kr//store/store_detail?storId=648
0
https://my.homeplus.co.kr//store/store_detail?storId=670
0
https://my.homeplus.co.kr//store/store_detail?storId=671
0
https://my.homeplus.co.kr//store/store_detail?storId=672
0
https://my.homeplus.co.kr//store/store_detail?storId=673
0
https://my.homeplus.co.kr//store/store_detail?storId=674
0
https://my.homeplus.co.kr//store/store_detail?storId=643
0
https://my.homeplus.co.kr//store/store_detail?storId=675
0
https://my.homeplus.co.kr//store/store_detail?storId=676
0
https://my.homeplus.co.kr//store/store_detail?storId=677
0
https://my.homeplus.co.kr//store/store_detail?storId=678
0
https://my.homeplus.co.kr//store/store_detail?storId=679
0
https://my.homeplus.co.kr//store/store_detail?storId=680
0
https://my.homeplus.co.kr//store/store_detail?storId=681
0
https://my.homeplus.co.kr//store/store_detail?storId=654
0
https://my.homeplus.co.kr//store/store_detail?storId=645
0
https://my.homeplus.co.kr//store/store_detail?storId=644
0
https://my.homeplus.co.kr//store/store_detail?storId=650
0
https://my.homeplus.co.kr//store/store_detail?storId=682
0
https://my.homeplus.co.kr//store/store_detail?storId=683
0
https://my.homeplus.co.kr//store/store_detail?storId=684
0
https://my.homeplus.co.kr//store/store_detail?storId=685
0
https://my.homeplus.co.kr//store/store_detail?storId=686
0
https://my.homeplus.co.kr//store/store_detail?storId=687
0
https://my.homeplus.co.kr//store/store_detail?storId=688
0
https://my.homeplus.co.kr//store/store_detail?storId=636
0
https://my.homeplus.co.kr//store/store_detail?storId=689
0
https://my.homeplus.co.kr//store/store_detail?storId=690
0
https://my.homeplus.co.kr//store/store_detail?storId=616
0
https://my.homeplus.co.kr//store/store_detail?storId=619
0
https://my.homeplus.co.kr//store/store_detail?storId=620
0
https://my.homeplus.co.kr//store/store_detail?storId=621
0
https://my.homeplus.co.kr//store/store_detail?storId=622
0
https://my.homeplus.co.kr//store/store_detail?storId=623
0
https://my.homeplus.co.kr//store/store_detail?storId=624
0
https://my.homeplus.co.kr//store/store_detail?storId=625
0
https://my.homeplus.co.kr//store/store_detail?storId=626
0
https://my.homeplus.co.kr//store/store_detail?storId=627
0
https://my.homeplus.co.kr//store/store_detail?storId=628
0
https://my.homeplus.co.kr//store/store_detail?storId=629
0
https://my.homeplus.co.kr//store/store_detail?storId=655
0
https://my.homeplus.co.kr//store/store_detail?storId=630
0
https://my.homeplus.co.kr//store/store_detail?storId=638
0
https://my.homeplus.co.kr//store/store_detail?storId=631
0
https://my.homeplus.co.kr//store/store_detail?storId=632
0
https://my.homeplus.co.kr//store/store_detail?storId=647
0
https://my.homeplus.co.kr//store/store_detail?storId=634
0
https://my.homeplus.co.kr//store/store_detail?storId=635
0

In [10]:
store_data = []  # 매장명과 도로명주소를 저장할 리스트

for link in links:
    driver1 = webdriver.Chrome()
    driver1.get(link)
    time.sleep(2)

    html = driver1.page_source
    soup = BeautifulSoup(html, "html.parser")

    # 매장명 가져오기
    store = soup.select_one("div.hp_wrap > div.hp_top > h2")
    store_name = store.get_text(strip=True)

    # 도로명 주소 가져오기
    content = soup.select_one("div.shop_mid dl.shop_detail_01.on > dd:nth-child(10)")
    address = content.get_text(strip=True).replace("길 찾기", "")

    # 튜플로 저장
    store_data.append((store_name, address))
    print(store_name, address)

    driver1.quit()

가양점 서울특별시 강서구 양천로 431
가좌점 인천광역시 서구 가정로 151번길 11
간석점 인천광역시 남동구 경원대로 971
강동점 서울특별시 강동구 양재대로 1571(메르디안 쇼핑센터)
강릉점 강원특별자치도 강릉시 경강로 2120
강서점 서울특별시 강서구 화곡로 398
거제점 경상남도 거제시 장평로 12
경기하남점 경기도 하남시 하남대로 747
경산점 경상북도 경산시 경안로 288
경주점 경상북도 경주시 공단로 97
계룡점 충청남도 계룡시 계룡대로 304
계산점 인천광역시 계양구 오조산 공원로 14
고양터미널점 경기도 고양시 일산동구 중앙로 1036
광양점 전라남도 광양시 항만11로 70
광주하남점 광주광역시 광산구 용아로 390
구미점 경상북도 구미시 구미대로 174
구월점 인천광역시 남동구 예술로 198
금천점 서울특별시 금천구 시흥대로 391
김제점 전북특별자치도 김제시 금성로 114
김포점 경기도 김포시 중봉로 14
김포풍무점 경기도 김포시 풍무로 167
김해점 경상남도 김해시 김해대로 2078
남대구점 대구광역시 남구 대명로 116
남양주진접점 경기도 남양주시 진접읍 장현리 216-1
내당점 대구광역시 서구 달구벌대로 1821
논산점 충청남도 논산시 시민로 187
대구수성점 대구광역시 수성구 동대구로 95
대전가오점 대전광역시 동구 은어송로 72
동광주점 광주광역시 북구 동문대로 200
동대문점 서울특별시 동대문구 천호대로 133
동래점 부산광역시 동래구 중앙대로 1523
동수원점 경기도 수원시 팔달구 효원로 257
동청주점 충청북도 청주시 청원구 충청대로 114 지하1층
동촌점 대구광역시 동구 동촌로 127
마산점 경상남도 창원시 마산회원구 삼호로 56
면목점 서울시 중랑구 사가정로 332 (면목동)
목포점 전라남도 목포시 영산로 313
문경점 경상북도 문경시 모전로 65
문화점 대전광역시 중구 계백로 1690
밀양점 경상남도 밀양시 점필재로 45
방학점 서울특별시 도봉구 도봉로 678
병점점 경기도 화성시 경기대로 985
보령점 충청남도 보령시 명암1길 17
부산감만점 부산광역시 남구 우암로 124
부산반여점 부산광역시 해운대구 선수촌로21번길 37  (반여동)
부산정관점 부산광역시 기장군 정관면 정관5로 50
부천상동점 경기도 부천시 원미구 길주로 118
부천소사점 경기 부천시 소사구 경인로 532
부천여월점 경기도 부천시 오정구 소사로 663
북수원점 경기도 수원시 장안구 경수대로 930
분당오리점 경기도 성남시 분당구 구미동 159
삼척점 강원특별자치도 삼척시 중앙로 258
삼천포점 경상남도 사천시 중앙로 165
상인점 대구광역시 달서구 월배로 183
서귀포점 제주특별자치도 서귀포시 중앙로 180
서부산점 부산광역시 사상구 광장로 7
서수원점 경기도 수원시 권선구 금곡동 160
서울남현점 서울시 관악구 과천대로 909
서울상봉점 서울특별시 중랑구 망우로 353
성서점 대구광역시 달서구 달구벌대로 1467
세종점 세종특별자치시 절재로 154
센텀시티점 부산광역시 해운대구 센텀동로 6
송탄점 경기도 평택시 경기대로 1103
순천점 전라남도 순천시 신월큰길 10
순천풍덕점 전라남도 순천시 팔마로 222
시화점 경기도 시흥시 희망공원로 269
시흥점 서울특별시 금천구 시흥대로 201
신내점 서울특별시 중랑구 신내로 201
신도림점 서울특별시 구로구 경인로 661
아시아드점 부산광역시 연제구 종합운동장로 7
안동점 경상북도 안동시 경동로 656
안산고잔점 경기도 안산시 단원구 광덕대로 175
안산선부점 경기도 안산시 단원구 삼일로 316
야탑점 경기도 성남시 분당구 성남대로925번길 16
영도점 부산광역시 영도구 대교로14번길 57
영등포점 서울특별시 영등포구 당산로 42
영주점 경상북도 영주시 대학로 29
영통점 경기도 수원시 영통구 봉영로 1576
오산점 경기도 오산시 수청동 610
오창점 충청북도 청주시 청원구 오창읍 중심상업1로 8-11
울산남구점 울산광역시 남구 수암로 148
울산동구점 울산광역시 동구 방어진 순환도로 637
울산북구점 울산광역시 북구 신답로 26
울산점 울산광역시 중구 번영로 475
원주점 강원특별자치도 원주시 치악로 1489
원천점 경기도 수원시 영통구 중부대로 437
월곡점 서울특별시 성북구 화랑로 76
월드컵점 서울시 마포구 성산동 515 홈플러스월드컵점
유성점 대전광역시 유성구 한밭대로 502
의정부점 경기도 의정부시 청사로 38
익산점 전북특별자치도 익산시 무왕로 1035
인천논현점 인천광역시 남동구 청능대로 596
인천송도점 인천광역시 연수구 송도동 168-3
인천숭의점 인천광역시 미추홀구 석정로 51
인천연수점 인천광역시 연수구 청능대로 210
인천청라점 인천광역시 서구 중봉대로 587
인하점 인천광역시 미추홀구 소성로 6
일산점 경기도 고양시 일산동구 중앙로 1275번길 64
작전점 인천광역시 계양구 계양대로 27
잠실점 서울특별시 송파구 올림픽로35가길 16
장림점 부산광역시 사하구 다대로 225
전주완산점 전북특별자치도 전주시 완산구 기린대로 170
전주점 전북특별자치도 전주시 덕진구 백제대로 771
전주효자점 전북특별자치도 전주시 완산구 용머리로 31
조치원점 세종특별자치시 조치원읍 허만석로 60
죽도점 경상북도 포항시 북구 중흥로 328
중계점 서울특별시 노원구 동일로 204가길 12
진주점 경상남도 진주시 대신로 304
진해점 경상남도 창원시 진해구 충장로 356
창원점 경상남도 창원시 의창구 창원대로 415
천안신방점 충청남도 천안시 동남구 신촌1길 23
천안점 충청남도 천안시 동남구 천안대로 574 (구성동)
청주성안점 충청북도 청주시 상당구 사직대로 346
청주점 충청북도 청주시 흥덕구 서부로 1291
춘천점 강원특별자치도 춘천시 김유정로 1840
칠곡점 대구광역시 북구 동암로12길 8
킨텍스점 경기도 고양시 일산서구 호수로 817
파주문산점 경기도 파주시 문산읍 방촌로 1759
파주운정점 경기도 파주시 청암로 17번길 17 (목동동927번지)
평촌점 경기도 안양시 동안구 동안로 162
평택안중점 경기도 평택시 안중읍 서동대로 1489
포천송우점 경기도 포천시 소흘읍 솔모루로 9
포항점 경상북도 포항시 남구 중흥로 77
합정점 서울시 마포구 양화로 45
화성동탄점 경기도 화성시 동탄중앙로 200
화성향남점 경기도 화성시 향남읍 향남로 402

In [11]:
store_data

[('가양점', '서울특별시 강서구 양천로 431'),
 ('가좌점', '인천광역시 서구 가정로 151번길 11'),
 ('간석점', '인천광역시 남동구 경원대로 971'),
 ('강동점', '서울특별시 강동구 양재대로 1571(메르디안 쇼핑센터)'),
 ('강릉점', '강원특별자치도 강릉시 경강로 2120'),
 ('강서점', '서울특별시 강서구 화곡로 398'),
 ('거제점', '경상남도 거제시 장평로 12'),
 ('경기하남점', '경기도 하남시 하남대로 747'),
 ('경산점', '경상북도 경산시 경안로 288'),
 ('경주점', '경상북도 경주시 공단로 97'),
 ('계룡점', '충청남도 계룡시 계룡대로 304'),
 ('계산점', '인천광역시 계양구 오조산 공원로 14'),
 ('고양터미널점', '경기도 고양시 일산동구 중앙로 1036'),
 ('광양점', '전라남도 광양시 항만11로 70'),
 ('광주하남점', '광주광역시 광산구 용아로 390'),
 ('구미점', '경상북도 구미시 구미대로 174'),
 ('구월점', '인천광역시 남동구 예술로 198'),
 ('금천점', '서울특별시 금천구 시흥대로 391'),
 ('김제점', '전북특별자치도 김제시 금성로 114'),
 ('김포점', '경기도 김포시 중봉로 14'),
 ('김포풍무점', '경기도 김포시 풍무로 167'),
 ('김해점', '경상남도 김해시 김해대로 2078'),
 ('남대구점', '대구광역시 남구 대명로 116'),
 ('남양주진접점', '경기도 남양주시 진접읍 장현리 216-1'),
 ('내당점', '대구광역시 서구 달구벌대로 1821'),
 ('논산점', '충청남도 논산시 시민로 187'),
 ('대구수성점', '대구광역시 수성구 동대구로 95'),
 ('대전가오점', '대전광역시 동구 은어송로 72'),
 ('동광주점', '광주광역시 북구 동문대로 200'),
 ('동대문점', '서울특별시 동대문구 천호대로 133'),
 ('동래점', '부산광역시 동래구 중앙대로 1523'),
 ('동수원점', '경기도 수원시 팔달구 효원로 257'),
 ('동청주점', '충청북도 청주시 청원구 충청대로 114 지하1층'),
 ('동촌점', '대구광역시 동구 동촌로 127'),
 ('마산점', '경상남도 창원시 마산회원구 삼호로 56'),
 ('면목점', '서울시 중랑구 사가정로 332 (면목동)'),
 ('목포점', '전라남도 목포시 영산로 313'),
 ('문경점', '경상북도 문경시 모전로 65'),
 ('문화점', '대전광역시 중구 계백로 1690'),
 ('밀양점', '경상남도 밀양시 점필재로 45'),
 ('방학점', '서울특별시 도봉구 도봉로 678'),
 ('병점점', '경기도 화성시 경기대로 985'),
 ('보령점', '충청남도 보령시 명암1길 17'),
 ('부산감만점', '부산광역시 남구 우암로 124'),
 ('부산반여점', '부산광역시 해운대구 선수촌로21번길 37  (반여동)'),
 ('부산정관점', '부산광역시 기장군 정관면 정관5로 50'),
 ('부천상동점', '경기도 부천시 원미구 길주로 118'),
 ('부천소사점', '경기 부천시 소사구 경인로 532'),
 ('부천여월점', '경기도 부천시 오정구 소사로 663'),
 ('북수원점', '경기도 수원시 장안구 경수대로 930'),
 ('분당오리점', '경기도 성남시 분당구 구미동 159'),
 ('삼척점', '강원특별자치도 삼척시 중앙로 258'),
 ('삼천포점', '경상남도 사천시 중앙로 165'),
 ('상인점', '대구광역시 달서구 월배로 183'),
 ('서귀포점', '제주특별자치도 서귀포시 중앙로 180'),
 ('서부산점', '부산광역시 사상구 광장로 7'),
 ('서수원점', '경기도 수원시 권선구 금곡동 160'),
 ('서울남현점', '서울시 관악구 과천대로 909'),
 ('서울상봉점', '서울특별시 중랑구 망우로 353'),
 ('성서점', '대구광역시 달서구 달구벌대로 1467'),
 ('세종점', '세종특별자치시 절재로 154'),
 ('센텀시티점', '부산광역시 해운대구 센텀동로 6'),
 ('송탄점', '경기도 평택시 경기대로 1103'),
 ('순천점', '전라남도 순천시 신월큰길 10'),
 ('순천풍덕점', '전라남도 순천시 팔마로 222'),
 ('시화점', '경기도 시흥시 희망공원로 269'),
 ('시흥점', '서울특별시 금천구 시흥대로 201'),
 ('신내점', '서울특별시 중랑구 신내로 201'),
 ('신도림점', '서울특별시 구로구 경인로 661'),
 ('아시아드점', '부산광역시 연제구 종합운동장로 7'),
 ('안동점', '경상북도 안동시 경동로 656'),
 ('안산고잔점', '경기도 안산시 단원구 광덕대로 175'),
 ('안산선부점', '경기도 안산시 단원구 삼일로 316'),
 ('야탑점', '경기도 성남시 분당구 성남대로925번길 16'),
 ('영도점', '부산광역시 영도구 대교로14번길 57'),
 ('영등포점', '서울특별시 영등포구 당산로 42'),
 ('영주점', '경상북도 영주시 대학로 29'),
 ('영통점', '경기도 수원시 영통구 봉영로 1576'),
 ('오산점', '경기도 오산시 수청동 610'),
 ('오창점', '충청북도 청주시 청원구 오창읍 중심상업1로 8-11'),
 ('울산남구점', '울산광역시 남구 수암로 148'),
 ('울산동구점', '울산광역시 동구 방어진 순환도로 637'),
 ('울산북구점', '울산광역시 북구 신답로 26'),
 ('울산점', '울산광역시 중구 번영로 475'),
 ('원주점', '강원특별자치도 원주시 치악로 1489'),
 ('원천점', '경기도 수원시 영통구 중부대로 437'),
 ('월곡점', '서울특별시 성북구 화랑로 76'),
 ('월드컵점', '서울시 마포구 성산동 515 홈플러스월드컵점'),
 ('유성점', '대전광역시 유성구 한밭대로 502'),
 ('의정부점', '경기도 의정부시 청사로 38'),
 ('익산점', '전북특별자치도 익산시 무왕로 1035'),
 ('인천논현점', '인천광역시 남동구 청능대로 596'),
 ('인천송도점', '인천광역시 연수구 송도동 168-3'),
 ('인천숭의점', '인천광역시 미추홀구 석정로 51'),
 ('인천연수점', '인천광역시 연수구 청능대로 210'),
 ('인천청라점', '인천광역시 서구 중봉대로 587'),
 ('인하점', '인천광역시 미추홀구 소성로 6'),
 ('일산점', '경기도 고양시 일산동구 중앙로 1275번길 64'),
 ('작전점', '인천광역시 계양구 계양대로 27'),
 ('잠실점', '서울특별시 송파구 올림픽로35가길 16'),
 ('장림점', '부산광역시 사하구 다대로 225'),
 ('전주완산점', '전북특별자치도 전주시 완산구 기린대로 170'),
 ('전주점', '전북특별자치도 전주시 덕진구 백제대로 771'),
 ('전주효자점', '전북특별자치도 전주시 완산구 용머리로 31'),
 ('조치원점', '세종특별자치시 조치원읍 허만석로 60'),
 ('죽도점', '경상북도 포항시 북구 중흥로 328'),
 ('중계점', '서울특별시 노원구 동일로 204가길 12'),
 ('진주점', '경상남도 진주시 대신로 304'),
 ('진해점', '경상남도 창원시 진해구 충장로 356'),
 ('창원점', '경상남도 창원시 의창구 창원대로 415'),
 ('천안신방점', '충청남도 천안시 동남구 신촌1길 23'),
 ('천안점', '충청남도 천안시 동남구 천안대로 574 (구성동)'),
 ('청주성안점', '충청북도 청주시 상당구 사직대로 346'),
 ('청주점', '충청북도 청주시 흥덕구 서부로 1291'),
 ('춘천점', '강원특별자치도 춘천시 김유정로 1840'),
 ('칠곡점', '대구광역시 북구 동암로12길 8'),
 ('킨텍스점', '경기도 고양시 일산서구 호수로 817'),
 ('파주문산점', '경기도 파주시 문산읍 방촌로 1759'),
 ('파주운정점', '경기도 파주시 청암로 17번길 17 (목동동927번지)'),
 ('평촌점', '경기도 안양시 동안구 동안로 162'),
 ('평택안중점', '경기도 평택시 안중읍 서동대로 1489'),
 ('포천송우점', '경기도 포천시 소흘읍 솔모루로 9'),
 ('포항점', '경상북도 포항시 남구 중흥로 77'),
 ('합정점', '서울시 마포구 양화로 45'),
 ('화성동탄점', '경기도 화성시 동탄중앙로 200'),
 ('화성향남점', '경기도 화성시 향남읍 향남로 402')]

In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame(store_data, columns=["매장명", "주소"])

In [16]:
df.to_excel("../Data/홈플러스_매장목록.xlsx", index=False)

In [20]:
df = pd.read_excel("../Data/홈플러스_매장목록.xlsx")
df.columns = ['매장명','도로명주소']
df.head()

   매장명                           도로명주소
0  가양점               서울특별시 강서구 양천로 431
1  가좌점           인천광역시 서구 가정로 151번길 11
2  간석점              인천광역시 남동구 경원대로 971
3  강동점  서울특별시 강동구 양재대로 1571(메르디안 쇼핑센터)
4  강릉점            강원특별자치도 강릉시 경강로 2120

In [22]:
# AIzaSyCVgO5pFBFOmriF06-81_LmRXtSAwgrjxM

!pip install googlemaps pandas openpyxl

Requirement already satisfied: googlemaps in /opt/anaconda3/lib/python3.12/site-packages (4.10.0)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: openpyxl in /opt/anaconda3/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: requests<3.0,>=2.20.0 in /opt/anaconda3/lib/python3.12/site-packages (from googlemaps) (2.32.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: et-xmlfile in /opt/anaconda3/lib/python3.12/site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2025.4.26)

In [23]:
import googlemaps
import time

In [24]:
# 1. Google Maps API 클라이언트 생성
gmaps = googlemaps.Client(key='AIzaSyCVgO5pFBFOmriF06-81_LmRXtSAwgrjxM')

# 2. 엑셀 파일 읽기
df = pd.read_excel("../Data/홈플러스_매장목록.xlsx")
df.columns = ['매장명', '도로명주소']

# 3. 위도, 경도 컬럼 추가
latitudes = []
longitudes = []

for address in df['도로명주소']:
    try:
        result = gmaps.geocode(address)
        if result:
            location = result[0]['geometry']['location']
            latitudes.append(location['lat'])
            longitudes.append(location['lng'])
        else:
            latitudes.append(None)
            longitudes.append(None)
    except Exception as e:
        print(f"에러 발생: {address}, {e}")
        latitudes.append(None)
        longitudes.append(None)
    time.sleep(0.5)  # 속도 제한 방지 (쿼터 초과 방지)

df['위도'] = latitudes
df['경도'] = longitudes

# 4. 엑셀로 저장
df.to_excel("../Data/홈플러스_매장목록_위경도포함.xlsx", index=False)

In [25]:
import folium
import pandas as pd

In [26]:
# 서울지도 만들기
seoul_map = folium.Map(
  location=[37.55, 126.95],
  zoom_start = 12
)
seoul_map

In [27]:
# 대학교 정보 가져오기
df = pd.read_excel("../Data/홈플러스_매장목록_위경도포함.xlsx")
df.columns = ['매장명','도로명주소','위도','경도']
df.head()

   매장명                           도로명주소         위도          경도
0  가양점               서울특별시 강서구 양천로 431  37.564269  126.850105
1  가좌점           인천광역시 서구 가정로 151번길 11  37.497618  126.670731
2  간석점              인천광역시 남동구 경원대로 971  37.469554  126.689014
3  강동점  서울특별시 강동구 양재대로 1571(메르디안 쇼핑센터)  37.545717  127.142251
4  강릉점            강원특별자치도 강릉시 경강로 2120  37.755701  128.898678

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   매장명     126 non-null    object
 1   도로명주소   126 non-null    object
 2   위도      126 non-null    float64
 3   경도      126 non-null    float64
dtypes: float64(2), object(2)
memory usage: 4.1+ KB

In [30]:
# 서울 지도에 학교 위치 표시하기
seoul_map = folium.Map(
  location=[37.55, 126.98],
  zoom_start=12
)

# 대학교 위치 정보를 Marker로 표시
for name, lat, lng in zip(df.매장명, df.위도, df.경도):
  popup = folium.Popup(name, max_width=200)
  folium.Marker(
    [lat,lng],
    popup=popup
  ).add_to(seoul_map)

  folium.CircleMarker(
    [lat,lng],
    radius=10,
    color='brown', # 원의 둘레 색상
    fill_color='coral',
    fill=True,
    fill_opacity=0.7
  ).add_to(seoul_map)

seoul_map

In [31]:
list(zip(df.매장명, df.위도, df.경도))

[('가양점', 37.5642688, 126.8501054),
 ('가좌점', 37.4976182, 126.6707307),
 ('간석점', 37.4695541, 126.6890144),
 ('강동점', 37.5457174, 127.1422509),
 ('강릉점', 37.7557014, 128.8986785),
 ('강서점', 37.5584079, 126.8550157),
 ('거제점', 34.8910652, 128.6165886),
 ('경기하남점', 37.53800510000001, 127.212624),
 ('경산점', 35.8328119, 128.7356657),
 ('경주점', 35.8731931, 129.2245882),
 ('계룡점', 36.2739942, 127.2571433),
 ('계산점', 37.5395037, 126.7362102),
 ('고양터미널점', 37.6432332, 126.7896989),
 ('광양점', 34.9283709, 127.6948095),
 ('광주하남점', 35.1779503, 126.8054081),
 ('구미점', 36.102771, 128.3637732),
 ('구월점', 37.45192979999999, 126.7018875),
 ('금천점', 37.4686843, 126.8968983),
 ('김제점', 35.799696, 126.9028623),
 ('김포점', 37.6238779, 126.6986605),
 ('김포풍무점', 37.6099441, 126.7236884),
 ('김해점', 35.2418274, 128.8701777),
 ('남대구점', 35.839019, 128.5702323),
 ('남양주진접점', 37.7215527, 127.1889272),
 ('내당점', 35.8605037, 128.5633072),
 ('논산점', 36.1835805, 127.09824),
 ('대구수성점', 35.8388009, 128.6232068),
 ('대전가오점', 36.3069371, 127.4580203),
 ('동광주점', 35.1795448, 126.930464),
 ('동대문점', 37.5745098, 127.0387891),
 ('동래점', 35.2212937, 129.0855784),
 ('동수원점', 37.26276610000001, 127.0301312),
 ('동청주점', 36.6667172, 127.4950373),
 ('동촌점', 35.8862248, 128.65563),
 ('마산점', 35.2226498, 128.5857481),
 ('면목점', 37.5799415, 127.0810446),
 ('목포점', 34.8059385, 126.3996537),
 ('문경점', 36.5873111, 128.1902745),
 ('문화점', 36.3202442, 127.4077244),
 ('밀양점', 35.4892449, 128.7404285),
 ('방학점', 37.6648415, 127.0437424),
 ('병점점', 37.2036885, 127.036705),
 ('보령점', 36.3439651, 126.6139016),
 ('부산감만점', 35.1214661, 129.0823255),
 ('부산반여점', 35.19652500000001, 129.1156644),
 ('부산정관점', 35.3230767, 129.1763584),
 ('부천상동점', 37.5043131, 126.7550039),
 ('부천소사점', 37.4848505, 126.8142873),
 ('부천여월점', 37.5158671, 126.8023384),
 ('북수원점', 37.3027243, 127.0087975),
 ('분당오리점', 37.3400457, 127.1069711),
 ('삼척점', 37.4463759, 129.1683249),
 ('삼천포점', 34.9404761, 128.0799584),
 ('상인점', 35.8181693, 128.5334098),
 ('서귀포점', 33.2605504, 126.560021),
 ('서부산점', 35.1642893, 128.9778086),
 ('서수원점', 37.2741955, 126.945457),
 ('서울남현점', 37.4714783, 126.9824131),
 ('서울상봉점', 37.5981008, 127.0905139),
 ('성서점', 35.8494718, 128.5274595),
 ('세종점', 36.5073165, 127.2588611),
 ('센텀시티점', 35.1709241, 129.1336628),
 ('송탄점', 37.0450097, 127.0595655),
 ('순천점', 34.9612229, 127.5202887),
 ('순천풍덕점', 34.9400591, 127.5090189),
 ('시화점', 37.3452813, 126.7250985),
 ('시흥점', 37.45189999999999, 126.9007973),
 ('신내점', 37.6157942, 127.0937634),
 ('신도림점', 37.5094204, 126.8877437),
 ('아시아드점', 35.19090449999999, 129.0614196),
 ('안동점', 36.5625734, 128.7295503),
 ('안산고잔점', 37.3119167, 126.8289421),
 ('안산선부점', 37.3337911, 126.8126004),
 ('야탑점', 37.4130943, 127.1273267),
 ('영도점', 35.0958984, 129.0442198),
 ('영등포점', 37.5182266, 126.8959242),
 ('영주점', 36.8091454, 128.6213432),
 ('영통점', 37.2517789, 127.0725411),
 ('오산점', 37.1701342, 127.061791),
 ('오창점', 36.7130181, 127.4282147),
 ('울산남구점', 35.5263914, 129.3228077),
 ('울산동구점', 35.4989422, 129.4274591),
 ('울산북구점', 35.6300759, 129.3448336),
 ('울산점', 35.5644319, 129.3346718),
 ('원주점', 37.3177406, 127.9673488),
 ('원천점', 37.2700876, 127.0636185),
 ('월곡점', 37.6018206, 127.0404453),
 ('월드컵점', 37.5677584, 126.8981147),
 ('유성점', 36.358467, 127.3543402),
 ('의정부점', 37.7521392, 127.0710487),
 ('익산점', 35.9589222, 126.9722905),
 ('인천논현점', 37.4005453, 126.7256012),
 ('인천송도점', 37.3801251, 126.6564153),
 ('인천숭의점', 37.4655406, 126.6619953),
 ('인천연수점', 37.4059785, 126.6837028),
 ('인천청라점', 37.5323161, 126.6486335),
 ('인하점', 37.4476859, 126.6507762),
 ('일산점', 37.6590437, 126.7688722),
 ('작전점', 37.5261761, 126.7212713),
 ('잠실점', 37.516256, 127.1030333),
 ('장림점', 35.0825417, 128.9783378),
 ('전주완산점', 35.8237137, 127.1500603),
 ('전주점', 35.8475105, 127.1529095),
 ('전주효자점', 35.8066177, 127.1140193),
 ('조치원점', 36.5863115, 127.2976346),
 ('죽도점', 36.0308806, 129.3651041),
 ('중계점', 37.6399182, 127.0686084),
 ('진주점', 35.187577, 128.1177058),
 ('진해점', 35.1531962, 128.6911405),
 ('창원점', 35.2341189, 128.6436851),
 ('천안신방점', 36.7871523, 127.1204631),
 ('천안점', 36.7968742, 127.1719945),
 ('청주성안점', 36.6362926, 127.4859783),
 ('청주점', 36.6154368, 127.4423096),
 ('춘천점', 37.8506225, 127.7347471),
 ('칠곡점', 35.9448492, 128.5559395),
 ('킨텍스점', 37.6679213, 126.7515016),
 ('파주문산점', 37.8692356, 126.7848805),
 ('파주운정점', 37.7295258, 126.7367655),
 ('평촌점', 37.393523, 126.9509172),
 ('평택안중점', 36.9902258, 126.9163792),
 ('포천송우점', 37.8242882, 127.1412881),
 ('포항점', 36.0127312, 129.348909),
 ('합정점', 37.5509344, 126.9137824),
 ('화성동탄점', 37.2027885, 127.0684595),
 ('화성향남점', 37.1307676, 126.9218289)]