### file 읽고 쓰기
파일 객체 = open(파일 이름, 파일 열기 모드)   
파일 열기 모드 : r(읽기), w(쓰기 = del + inst), a(추가)

In [1]:
# 파일 쓰기모드로 열어 출력값 저장하기.
f = open("../Data/new.txt", "w")
for i in range(1, 10+1):
  f.write(f"{i}번째 줄 입니다.\n")
f.close()

In [3]:
# 파일을 읽기모드로 열어 파일 내용 출력하기 - Method 1

f = open("../Data/new.txt", "r")
while True:
  line = f.readline()
  if not line:
    break
  print(line, end="")
f.close

1번째 줄 입니다.
2번째 줄 입니다.
3번째 줄 입니다.
4번째 줄 입니다.
5번째 줄 입니다.
6번째 줄 입니다.
7번째 줄 입니다.
8번째 줄 입니다.
9번째 줄 입니다.
10번째 줄 입니다.

In [4]:
# 파일을 읽기모드로 열어 파일 내용 출력하기 - Method 2

f = open("../Data/new.txt", "r")
lines = f.readlines()
f.close()
for line in lines:
  print(line, end="")

1번째 줄 입니다.
2번째 줄 입니다.
3번째 줄 입니다.
4번째 줄 입니다.
5번째 줄 입니다.
6번째 줄 입니다.
7번째 줄 입니다.
8번째 줄 입니다.
9번째 줄 입니다.
10번째 줄 입니다.

In [ ]:
# 파일을 읽기모드로 열어 파일 내용 출력하기 - Method 3

f = open("../Data/new.txt", "r")
data = f.read() # 메모리를 가져오자
f.close()
print(data)

1번째 줄 입니다.
2번째 줄 입니다.
3번째 줄 입니다.
4번째 줄 입니다.
5번째 줄 입니다.
6번째 줄 입니다.
7번째 줄 입니다.
8번째 줄 입니다.
9번째 줄 입니다.
10번째 줄 입니다.

In [6]:
# 파일에 새로운 내용 추가하기
f = open("../Data/new.txt", "a")
for i in range(11, 20+1):
  f.write(f"{i}번째 줄 입니다.\n")
f.close()

In [8]:
# 파일을 읽기모드로 열어 파일 내용 출력하기 - Method 3

f = open("../Data/new.txt", "r")
data = f.read() # 메모리를 가져오자
f.close()
print(data)

1번째 줄 입니다.
2번째 줄 입니다.
3번째 줄 입니다.
4번째 줄 입니다.
5번째 줄 입니다.
6번째 줄 입니다.
7번째 줄 입니다.
8번째 줄 입니다.
9번째 줄 입니다.
10번째 줄 입니다.
11번째 줄 입니다.
12번째 줄 입니다.
13번째 줄 입니다.
14번째 줄 입니다.
15번째 줄 입니다.
16번째 줄 입니다.
17번째 줄 입니다.
18번째 줄 입니다.
19번째 줄 입니다.
20번째 줄 입니다.

---
### with문
: 파일의 열고 닫음을 자동으로 처리하기 위해 with문을 벗어나면 자동으로 close()

In [9]:
# 파일 만들기
with open("../Data/new2.txt", "w") as f:
  for i in range(1, 10+1):
    f.write(f"{i}번째 줄 입니다.\n")

In [12]:
# 파일 읽기
with open("../Data/new2.txt", "r") as f:
  data = f.read() # 메모리를 가져오자
  print(data)

1번째 줄 입니다.
2번째 줄 입니다.
3번째 줄 입니다.
4번째 줄 입니다.
5번째 줄 입니다.
6번째 줄 입니다.
7번째 줄 입니다.
8번째 줄 입니다.
9번째 줄 입니다.
10번째 줄 입니다.

---
### Pandas

In [13]:
import pandas as pd

In [ ]:
# 불러오기
textSample = pd.read_table("../Data/new.txt", header=None)
textSample.head() # 5줄을 찍는다.

            0
0  1번째 줄 입니다.
1  2번째 줄 입니다.
2  3번째 줄 입니다.
3  4번째 줄 입니다.
4  5번째 줄 입니다.

In [19]:
# 저장하기
textSample.to_string("../Data/sample_file.txt", index=False, header=None) # txt파일이니까.

In [20]:
pd.read_table("../Data/sample_file.txt", header=None).head()

             0
0   1번째 줄 입니다.
1   2번째 줄 입니다.
2   3번째 줄 입니다.
3   4번째 줄 입니다.
4   5번째 줄 입니다.