### Folium : 지도 활용
: 세계지도를 기본으로 한다

In [1]:
!pip install folium

Requirement already satisfied: folium in /opt/anaconda3/lib/python3.12/site-packages (0.20.0)
Requirement already satisfied: branca>=0.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in /opt/anaconda3/lib/python3.12/site-packages (from folium) (3.1.4)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.12/site-packages (from folium) (1.26.4)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in /opt/anaconda3/lib/python3.12/site-packages (from folium) (2022.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2>=2.9->folium) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium) (2025.4.26)

In [2]:
import folium
import pandas as pd

In [3]:
# 서울지도 만들기
seoul_map = folium.Map(
  location=[37.55, 126.95],
  zoom_start = 12
)
seoul_map

In [4]:
# 지도를 html로 저장하기
seoul_map.save("../Data/seoul.html")

---
### 지도에 마커 표시하기
: 서울시내 주요 대학교의 위치를 표시하기

In [5]:
# 대학교 정보 가져오기
df = pd.read_excel("../Data/서울지역 대학교 위치.xlsx")
df.columns = ['학교명','위도','경도']
df.head()

            학교명         위도          경도
0  KAIST 서울캠퍼스   37.592573  127.046737
1         KC대학교  37.548345  126.854797
2  가톨릭대학교(성신교정)  37.585922  127.004328
3  가톨릭대학교(성의교정)  37.499623  127.006065
4      감리교신학대학교  37.567645  126.961610

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학교명     47 non-null     object
 1   위도      47 non-null     float64
 2   경도      47 non-null     float64
dtypes: float64(2), object(1)
memory usage: 1.2+ KB

In [7]:
# 서울 지도에 학교 위치 표시하기
seoul_map = folium.Map(
  location=[37.55, 126.98],
  zoom_start=12
)

# 대학교 위치 정보를 Marker로 표시
for name, lat, lng in zip(df.학교명, df.위도, df.경도):
  popup = folium.Popup(name, max_width=200)
  folium.Marker(
    [lat,lng],
    popup=popup
  ).add_to(seoul_map)

  folium.CircleMarker(
    [lat,lng],
    radius=10,
    color='brown', # 원의 둘레 색상
    fill_color='coral',
    fill=True,
    fill_opacity=0.7
  ).add_to(seoul_map)

seoul_map

In [8]:
list(zip(df.학교명, df.위도, df.경도))

[('KAIST 서울캠퍼스 ', 37.592573, 127.046737),
 ('KC대학교', 37.5483449, 126.8547974),
 ('가톨릭대학교(성신교정)', 37.5859218, 127.0043275),
 ('가톨릭대학교(성의교정)', 37.4996227, 127.0060653),
 ('감리교신학대학교', 37.5676455, 126.96161),
 ('건국대학교', 37.5407625, 127.0793428),
 ('경기대학교 서울캠퍼스 ', 37.300485, 127.035833),
 ('경희대학교 서울캠퍼스 ', 37.5961951, 127.052544),
 ('고려대학교', 37.588556165888, 127.01998189277),
 ('광운대학교', 37.6194965, 127.0596958),
 ('국민대학교', 37.6096409, 126.997697),
 ('덕성여자대학교', 37.6511988, 127.0161604),
 ('동국대학교', 37.5574771, 127.0020518),
 ('동덕여자대학교', 37.6063202, 127.041808),
 ('명지대학교 서울캠퍼스 ', 37.5802046, 126.9234451),
 ('삼육대학교', 37.6429515, 127.1054757),
 ('상명대학교\xa0서울캠퍼스 ', 37.602638, 126.955252),
 ('서강대학교', 37.5509442, 126.9410023),
 ('서경대학교', 37.615095, 127.0131113),
 ('서울과학기술대학교', 37.6316684, 127.0774813),
 ('서울교육대학교', 37.4899615, 127.0164124),
 ('서울기독대학교', 37.6009228, 126.9123818),
 ('서울대학교', 37.459882, 126.9519053),
 ('서울시립대학교', 37.5838657, 127.0587771),
 ('서울여자대학교', 37.6281126, 127.0904568),
 ('서울한영대학교', 37.4965411, 126.8512616),
 ('성공회대학교', 37.4872325, 126.8253202),
 ('성균관대학교 서울캠퍼스 \xa0', 37.588227, 126.993606),
 ('성신여자대학교', 37.5913103, 127.0221312),
 ('세종대학교', 37.5502596, 127.073139),
 ('숙명여자대학교', 37.5463644, 126.9648311),
 ('숭실대학교', 37.4963111, 126.9574596),
 ('연세대학교', 37.565784, 126.938572),
 ('육군사관학교', 37.6238188, 127.0988783),
 ('이화여자대학교', 37.5643079, 126.9501786),
 ('장로회신학대학교', 37.5505112, 127.1034577),
 ('중앙대학교 서울캠퍼스 ', 37.5050881, 126.9571012),
 ('총신대학교', 37.4886232, 126.9668169),
 ('추계예술대학교', 37.5624515, 126.9534165),
 ('한국방송통신대학교', 37.5786127, 127.0032905),
 ('한국성서대학교', 37.6487485, 127.0643199),
 ('한국예술종합학교', 37.6049973, 127.0567397),
 ('한국외국어대학교', 37.597319, 127.057843),
 ('한국체육대학교', 37.5196266, 127.1309837),
 ('한성대학교', 37.5817849, 127.010369),
 ('한양대학교', 37.5572321, 127.0453219),
 ('홍익대학교', 37.5514642, 126.9250106)]

---
#### 지도 영역에 단계 구분표(Choropleth Map) 표시하기
: 행정구역과 같이 지도상의 어떤 경계에 둘러싸인 영역에 색을 칠하거나 음영등의 정보를 시각화 하는 기법

In [9]:
import json

In [10]:
df = pd.read_excel("../Data/경기도인구데이터.xlsx", index_col='구분')
df.head()

,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
구분,,,,,,,,,,,
수원시장안구,287474,285803,290798,293692,290999,291757,300908,301196,299016,296479,293828
수원시권선구,310553,308177,304097,306783,321176,332633,331773,339835,351053,358393,365653
수원시팔달구,216945,213235,219833,216503,209772,206794,204805,203479,199180,198515,193311
수원시영통구,252730,260210,258421,260557,266542,289074,310671,329718,335375,340654,349836
성남시수정구,256744,248452,242161,241070,236123,233997,228167,223539,219531,232841,236932

In [11]:
df.shape

(44, 11)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44 entries, 수원시장안구 to 양평군
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2007    44 non-null     int64
 1   2008    44 non-null     int64
 2   2009    44 non-null     int64
 3   2010    44 non-null     int64
 4   2011    44 non-null     int64
 5   2012    44 non-null     int64
 6   2013    44 non-null     int64
 7   2014    44 non-null     int64
 8   2015    44 non-null     int64
 9   2016    44 non-null     int64
 10  2017    44 non-null     int64
dtypes: int64(11)
memory usage: 4.1+ KB

In [15]:
# 경기도 시군구 경계 데이터
geo_path = "../Data/경기도행정구역경계.json"
geo_data = json.load(
  open(geo_path, encoding='utf-8')
)
geo_data

{'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'properties': {'code': 31380,
    'name': '양평군',
    'name_eng': 'Yangpyeong-gun',
    'base_year': 2013},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[127.56113535909492, 37.6256560539258],
      [127.57290963929243, 37.61087369350498],
      [127.56366973908277, 37.5842624297699],
      [127.52226606559191, 37.5828628697518],
      [127.50048767007603, 37.569036373178626],
      [127.47687473909174, 37.574448241913856],
      [127.47565866803647, 37.60512112601634],
      [127.44699730711024, 37.64497584741164],
      [127.4272349102434, 37.66284420898682],
      [127.40156700708162, 37.64806970784708],
      [127.3732642199939, 37.6453987554284],
      [127.3542931884407, 37.6250006376975],
      [127.34360057873045, 37.588997440929354],
      [127.31002843450217, 37.53523876142835],
      [127.30923294884336, 37.5135706079458],
      [127.32809611134748, 37.53133849534739],
      [127.3663244453597, 37.52716845880826],
      [127.38286320755414, 37.50147517965334],
      [127.39046783039153, 37.47413422098595],
      [127.37490698722792, 37.455072688441305],
      [127.39174400683049, 37.4256483411369],
      [127.40276739880215, 37.41856433413549],
      [127.4250053080982, 37.43669952587185],
      [127.4817900304572, 37.42084413829662],
      [127.51015267026155, 37.43699555518635],
      [127.52501209957308, 37.43192043868044],
      [127.53910572062166, 37.40849283821634],
      [127.60528700481163, 37.416969769508924],
      [127.63754040237271, 37.41065607591271],
      [127.6491838950862, 37.402042953108506],
      [127.66976823475012, 37.40884431255766],
      [127.71071536074867, 37.40736583858037],
      [127.70347417929173, 37.371054026073324],
      [127.76165381178268, 37.36421926003675],
      [127.77952402154285, 37.368441789396854],
      [127.80397287036232, 37.432516049235865],
      [127.79833492163134, 37.460500237870505],
      [127.77664798308412, 37.48883635932707],
      [127.77611527652192, 37.50328615763377],
      [127.80855972024105, 37.53220450961153],
      [127.8445769305193, 37.53621789699497],
      [127.85162286006927, 37.55037340096326],
      [127.81507964099751, 37.5618389022189],
      [127.79492564827493, 37.58252978378627],
      [127.76838776707211, 37.580178216134605],
      [127.75614914198108, 37.589477424718204],
      [127.7102810556826, 37.58360128682645],
      [127.69869383868397, 37.59757031454811],
      [127.65553070991882, 37.61954565135447],
      [127.62972032693943, 37.63983122973888],
      [127.60450569091653, 37.648548552427314],
      [127.58166701442097, 37.63033393389168],
      [127.56113535909492, 37.6256560539258]]]}},
  {'type': 'Feature',
   'properties': {'code': 31370,
    'name': '가평군',
    'name_eng': 'Gapyeong-gun',
    'base_year': 2013},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[127.44780328408541, 38.048238751068475],
      [127.42042182072485, 38.01200319871128],
      [127.41516664705571, 37.995046525366845],
      [127.39194666896421, 37.97992649728499],
      [127.37828420492166, 37.958773972665476],
      [127.3864253692493, 37.940789082655876],
      [127.35796486335995, 37.918888706648104],
      [127.33112989323685, 37.9192732427266],
      [127.32585628843694, 37.8708665787365],
      [127.31427495278925, 37.86338279582678],
      [127.29023239060183, 37.867156223189305],
      [127.27621937205707, 37.823925522993584],
      [127.28134774958465, 37.81350552459983],
      [127.2686525155809, 37.777676803810074],
      [127.32070791913966, 37.76445271893134],
      [127.34501289752937, 37.7266690692075],
      [127.35759057077398, 37.720909295881434],
      [127.35557114419971, 37.701041217064585],
      [127.38133544278186, 37.67180837890239],
      [127.3732642199939, 37.6453987554284],
      [127.40156700708162, 37.64806970784708],
      [127.4272349102434, 37.66284420898682],
      [127.44699730711024, 37.64497584741164],
      [127.47565866803647, 37.60512112601634],
      [127.47687473909174, 37.574448241913856],
      [127.50048767007603, 37.569036373178626],
      [127.52226606559191, 37.5828628697518],
      [127.56366973908277, 37.5842624297699],
      [127.57290963929243, 37.61087369350498],
      [127.56113535909492, 37.6256560539258],
      [127.53917031861263, 37.64021056192394],
      [127.5549605217701, 37.658757758392326],
      [127.55230133599949, 37.6826768602848],
      [127.5620152520609, 37.72573118147031],
      [127.54295591487076, 37.71630823574417],
      [127.50979807707056, 37.72791553253582],
      [127.5466892772679, 37.757547899640265],
      [127.52374487270039, 37.788564076302706],
      [127.53790811514408, 37.806297142430786],
      [127.5278056459557, 37.8205934650677],
      [127.53467866263196, 37.8391134107185],
      [127.5645808687282, 37.852710085354005],
      [127.586513542654, 37.87296654527047],
      [127.60326048844294, 37.87185797528634],
      [127.61988365348992, 37.90376621474279],
      [127.61592274592837, 37.93662873141094],
      [127.60515472290533, 37.95233960186072],
      [127.54648191805605, 37.96536690082484],
      [127.54189684816376, 37.99843118565868],
      [127.50356426725331, 37.99680815824825],
      [127.47430810833019, 38.00331531710267],
      [127.46013793737187, 38.01348603532302],
      [127.44780328408541, 38.048238751068475]]]}},
  {'type': 'Feature',
   'properties': {'code': 31350,
    'name': '연천군',
    'name_eng': 'Yeoncheon-gun',
    'base_year': 2013},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[127.1114029794941, 38.289324698353205],
      [127.07249919657463, 38.26801218962005],
      [127.02801007414642, 38.254549706273764],
      [126.99286312502117, 38.234131621017674],
      [126.97740008434542, 38.23136042526893],
      [126.98606173199121, 38.209401424377816],
      [126.96711105593987, 38.19506065700263],
      [126.95459011862387, 38.20786522832632],
      [126.92781480981668, 38.200854654628984],
      [126.8974333001951, 38.20180521598681],
      [126.87506682979435, 38.220357253330604],
      [126.8278790877819, 38.195486974451406],
      [126.77187664076929, 38.15202258772112],
      [126.75014823067355, 38.125072772241225],
      [126.78709379586621, 38.09626689678258],
      [126.79823368085893, 38.079396242822355],
      [126.85234589355446, 38.09221072381945],
      [126.86904468579002, 38.077582436479354],
      [126.89538167413222, 38.071648142471204],
      [126.89492205681401, 38.04859999954147],
      [126.87463524911628, 38.01581963256826],
      [126.85568764143953, 38.02873639803942],
      [126.83392985136591, 38.03100700061125],
      [126.8252320653152, 38.00913397816309],
      [126.83164256576254, 37.99035429677792],
      [126.8029965558113, 37.989251239637596],
      [126.80659958939793, 37.9680012097748],
      [126.8388723334759, 37.96197909365746],
      [126.8423229135476, 37.97819760433225],
      [126.85859300440933, 37.98329485669624],
      [126.8739356423477, 37.968400924665225],
      [126.89755470110721, 37.9683523617657],
      [126.90034044420747, 37.99438948257985],
      [126.93929997962098, 37.9789601448141],
      [126.97166918547234, 38.000587999007735],
      [126.99425287672854, 38.000624488107924],
      [127.01739022262282, 37.989561835400195],
      [126.97545924731331, 37.93928140597955],
      [127.01215278654801, 37.924817815480985],
      [127.02968085272437, 37.9404013715077],
      [127.05589127856165, 37.978154747876275],
      [127.09382742820131, 37.968691278173],
      [127.09290535753887, 37.98459431234087],
      [127.12231622589134, 37.976745791642564],
      [127.14982270353039, 37.99413348520078],
      [127.1474423860908, 38.01290337564081],
      [127.11440133420174, 38.04821685684721],
      [127.14326850224882, 38.070002354405226],
      [127.15086136346409, 38.05496212563221],
      [127.1888339288906, 38.06204029940796],
      [127.19437916578538, 38.0797568774465],
      [127.17503254383571, 38.13882932478672],
      [127.18150182398624, 38.181927191525546],
      [127.16857086007771, 38.19681089627724],
      [127.16461628401596, 38.22949766461027],
      [127.15063615800273, 38.239791315402336],
      [127.13243747984255, 38.22986476152822],
      [127.11224663908298, 38.23944312080941],
      [127.11610682730382, 38.26255766722931],
      [127.1114029794941, 38.289324698353205]]]}},
  {'type': 'Feature',
   'properties': {'code': 31280,
    'name': '여주시',
    'name_eng': 'Yeoju-si',
    'base_year': 2013},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[127.40276739880215, 37.41856433413549],
      [127.41955611640327, 37.386674887879835],
      [127.44514756834636, 37.3842770721951],
      [127.44459662819855, 37.35562085049101],
      [127.47263652805968, 37.35869263849808],
      [127.49167370715485, 37.339527598960764],
      [127.51574229064994, 37.336561285567946],
      [127.54853754663094, 37.29860192066929],
      [127.53106721989582, 37.27115011578052],
      [127.5395160453677, 37.24379045683148],
      [127.52770097674612, 37.23765094459253],
      [127.53342604855668, 37.19715010635273],
      [127.51957698997381, 37.18188687027366],
      [127.52893461217018, 37.170618598276],
      [127.55830514005798, 37.17381401041668],
      [127.5785248984445, 37.186311208078585],
      [127.5999013564347, 37.1854997199498],
      [127.63091754409567, 37.150947430524305],
      [127.66246837559255, 37.13682554779843],
      [127.69759568854894, 37.137598675963744],
      [127.6981539994774, 37.14931076846793],
      [127.73893911466041, 37.20715818139463],
      [127.75008528183503, 37.21383642183904],
      [127.75102511570132, 37.24464129242011],
      [127.76047537750615, 37.25518935399549],
      [127.75697503302167, 37.29496921027118],
      [127.77073902372764, 37.30499906774147],
      [127.76193527300671, 37.32724708852886],
      [127.76165381178268, 37.36421926003675],
      [127.70347417929173, 37.371054026073324],
      [127.71071536074867, 37.40736583858037],
      [127.66976823475012, 37.40884431255766],
      [127.6491838950862, 37.402042953108506],
      [127.63754040237271, 37.41065607591271],
      [127.60528700481163, 37.416969769508924],
      [127.53910572062166, 37.40849283821634],
      [127.52501209957308, 37.43192043868044],
      [127.51015267026155, 37.43699555518635],
      [127.4817900304572, 37.42084413829662],
      [127.4250053080982, 37.43669952587185],
      [127.40276739880215, 37.41856433413549]]]}},
  {'type': 'Feature',
   'properties': {'code': 31270,
    'name': '포천시',
    'name_eng': 'Pocheonsi',
    'base_year': 2013},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[127.18150182398624, 38.181927191525546],
      [127.17503254383571, 38.13882932478672],
      [127.19437916578538, 38.0797568774465],
      [127.1888339288906, 38.06204029940796],
      [127.15086136346409, 38.05496212563221],
      [127.14326850224882, 38.070002354405226],
      [127.11440133420174, 38.04821685684721],
      [127.1474423860908, 38.01290337564081],
      [127.14982270353039, 37.99413348520078],
      [127.12231622589134, 37.976745791642564],
      [127.09290535753887, 37.98459431234087],
      [127.09382742820131, 37.968691278173],
      [127.1240834119586, 37.913726790414486],
      [127.1480788721724, 37.909108279220675],
      [127.15777209998105, 37.89291633342494],
      [127.14908802054492, 37.87326470277757],
      [127.13067707221735, 37.87115064756639],
      [127.1113003891929, 37.85708813371199],
      [127.12400943178396, 37.82538075264934],
      [127.12412178020936, 37.80931541475853],
      [127.10645686970089, 37.776897580693586],
      [127.14177735342194, 37.76129795333661],
      [127.14882403466048, 37.75206030443599],
      [127.17524551122212, 37.751938183429424],
      [127.18575971970597, 37.76186443408089],
      [127.21510645674604, 37.75873586709106],
      [127.22719439323131, 37.750666435161854],
      [127.26186907661463, 37.765678541736996],
      [127.2686525155809, 37.777676803810074],
      [127.28134774958465, 37.81350552459983],
      [127.27621937205707, 37.823925522993584],
      [127.29023239060183, 37.867156223189305],
      [127.31427495278925, 37.86338279582678],
      [127.32585628843694, 37.8708665787365],
      [127.33112989323685, 37.9192732427266],
      [127.35796486335995, 37.918888706648104],
      [127.3864253692493, 37.940789082655876],
      [127.37828420492166, 37.958773972665476],
      [127.39194666896421, 37.97992649728499],
      [127.41516664705571, 37.995046525366845],
      [127.42042182072485, 38.01200319871128],
      [127.44780328408541, 38.048238751068475],
      [127.44645416125843, 38.09506926769056],
      [127.43271157644212, 38.11254491261849],
      [127.38575924845978, 38.111650021865444],
      [127.32332897924549, 38.09248746131129],
      [127.31342794935864, 38.113239178580145],
      [127.28533797240796, 38.11374536112377],
      [127.27790641954418, 38.13449032094295],
      [127.28937067741944, 38.1495974983685],
      [127.29146727692374, 38.17417076323154],
      [127.27319981021783, 38.1790866530056],
      [127.25802935713429, 38.16048880005979],
      [127.22539552047925, 38.144128217872485],
      [127.19211744512407, 38.157963139766544],
      [127.18150182398624, 38.181927191525546]]]}},
  {'type': 'Feature',
   'properties': {'code': 31260,
    'name': '양주시',
    'name_eng': 'Yangjusi',
    'base_year': 2013},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[126.97545924731331, 37.93928140597955],
      [126.94883433502994, 37.89688479787927],
      [126.9484401545115, 37.86422401203834],
      [126.93661135445112, 37.843479475117995],
      [126.9160273881691, 37.83830532663158],
      [126.9073114617216, 37.790560159793145],
      [126.93838979622467, 37.771436009953916],
      [126.93180653905974, 37.74575671706106],
      [126.92470886562188, 37.72916078041937],
      [126.92290257733573, 37.66907383915535],
      [126.94191948970435, 37.66797237250146],
      [126.94689093217877, 37.68234333447953],
      [126.96734461801938, 37.68969305565268],
      [126.99383903424, 37.676681761199085],
      [127.01039666042071, 37.681894589603594],
      [127.01795099203432, 37.69824412775662],
      [127.01477890845196, 37.722832167524864],
      [127.00430024727942, 37.73792676357612],
      [127.00437834122181, 37.75999833868866],
      [127.02081299427202, 37.76581418787214],
      [127.05297245855259, 37.75816755994106],
      [127.10645686970089, 37.776897580693586],
      [127.12412178020936, 37.80931541475853],
      [127.12400943178396, 37.82538075264934],
      [127.1113003891929, 37.85708813371199],
      [127.09509254572018, 37.86843288571378],
      [127.06250430862417, 37.86658619508279],
      [127.04837406784853, 37.891090496591005],
      [127.01281974367026, 37.90171539201257],
      [127.01215278654801, 37.924817815480985],
      [126.97545924731331, 37.93928140597955]]]}},
  {'type': 'Feature',
   'properties': {'code': 31250,
    'name': '광주시',
    'name_eng': 'Gwangju',
    'base_year': 2013},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[127.30923294884336, 37.5135706079458],
      [127.28971082577908, 37.51069218442014],
      [127.25539313999657, 37.50044702706516],
      [127.26066872639333, 37.4867746581613],
      [127.23892819551556, 37.47240158876339],
      [127.21785285379218, 37.479493796173465],
      [127.1831716097913, 37.47048077053623],
      [127.19808034941583, 37.441066604883545],
      [127.19594474070001, 37.421269309284035],
      [127.17637586604776, 37.40261052326208],
      [127.15506886795262, 37.36076173403712],
      [127.13605700285002, 37.35565614606753],
      [127.13845652996186, 37.336816804055495],
      [127.1439713536275, 37.33349026702227],
      [127.19373839709431, 37.34441869868583],
      [127.21042746205282, 37.32805374935785],
      [127.23072982952925, 37.35607967407726],
      [127.26708575818817, 37.33990127392118],
      [127.28543362549937, 37.3425335272208],
      [127.2795205391003, 37.306809952638524],
      [127.28383871402815, 37.2658807760632],
      [127.32142008240551, 37.27215636613311],
      [127.34092967480524, 37.26770614318737],
      [127.34227600003884, 37.28528169366774],
      [127.37829628277709, 37.317936247676194],
      [127.38906532153541, 37.31608103967859],
      [127.42277946655206, 37.33526375647856],
      [127.44459662819855, 37.35562085049101],
      [127.44514756834636, 37.3842770721951],
      [127.41955611640327, 37.386674887879835],
      [127.40276739880215, 37.41856433413549],
      [127.39174400683049, 37.4256483411369],
      [127.37490698722792, 37.455072688441305],
      [127.39046783039153, 37.47413422098595],
      [127.38286320755414, 37.50147517965334],
      [127.3663244453597, 37.52716845880826],
      [127.32809611134748, 37.53133849534739],
      [127.30923294884336, 37.5135706079458]]]}},
  {'type': 'Feature',
   'properties': {'code': 31240,
    'name': '화성시',
    'name_eng': 'Hwaseongsi',
    'base_year': 2013},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[126.92946761531998, 37.275967848758626],
      [126.9159468889861, 37.28864104563552],
      [126.84641021832398, 37.26433293772644],
      [126.81930541992186, 37.29590550406618],
      [126.77604675292967, 37.28552626562424],
      [126.76918029785156, 37.28334098034544],
      [126.73210144042969, 37.29098920118597],
      [126.71836853027344, 37.286072577028555],
      [126.68403625488283, 37.267495764381856],
      [126.6510772705078, 37.25328687335229],
      [126.66481018066405, 37.21994010868952],
      [126.65794372558594, 37.19478361329807],
      [126.66271935011406, 37.15926986163073],
      [126.6846290670714, 37.14600860455114],
      [126.67514463500929, 37.13507063838445],
      [126.69054868899676, 37.11326932983634],
      [126.7301407699343, 37.135914524793805],
      [126.74720764160156, 37.14225609389272],
      [126.7719268798828, 37.14663478158564],
      [126.79458618164062, 37.14827672411748],
      [126.80659259648279, 37.148624224069174],
      [126.7547607421875, 37.137329767248794],
      [126.72454833984374, 37.11543110112874],
      [126.73072814941408, 37.092430683283474],
      [126.7327880859375, 37.07544970503028],
      [126.75132751464844, 37.0601087778919],
      [126.75044219493901, 37.04618007006251],
      [126.75308052062115, 37.02639369248519],
      [126.79113814421088, 37.02631450535446],
      [126.79899352215931, 37.0092005991418],
      [126.84014623559027, 37.01079503386266],
      [126.85940022959993, 37.022131594683266],
      [126.8846211892453, 37.05795114472113],
      [126.90291323437098, 37.06724127811693],
      [126.94247588185057, 37.057958386286046],
      [126.95290081243859, 37.06545814826726],
      [126.98672297136514, 37.06879655242586],
      [127.00102521866197, 37.08973596266607],
      [127.00593012741142, 37.124105707924144],
      [127.03746950511537, 37.13336771678679],
      [127.03019615684671, 37.16027870494751],
      [127.00186863458882, 37.1747343711991],
      [127.02929563655235, 37.19787494412135],
      [127.06660498380589, 37.19589230774365],
      [127.07609473440765, 37.16092553278145],
      [127.09596808287752, 37.1566082978686],
      [127.10575417734016, 37.1407283236673],
      [127.12480483538663, 37.14166379699704],
      [127.13469226704495, 37.165565916914176],
      [127.16278322754954, 37.17771519608909],
      [127.15371679380591, 37.215705679231036],
      [127.09106338919456, 37.21351968359228],
      [127.06878518378286, 37.23731339587258],
      [127.04178611512381, 37.24066886027782],
      [127.02475029106094, 37.22207898080851],
      [126.97491964707861, 37.22588531228192],
      [126.95229769733274, 37.2524826245201],
      [126.93110125729105, 37.260824951129344],
      [126.92946761531998, 37.275967848758626]]]}},
  {'type': 'Feature',
   'properties': {'code': 31230,
    'name': '김포시',
    'name_eng': 'Gimpo-si',

In [23]:
geo_data['features'][0]['properties']['name']

'양평군'

In [30]:
# 경기도 지도 만들기
g_map = folium.Map(
  location = [37.55, 126.98],
  zoom_start=9
)

# 출력할 연도

year = 2007

# Choropleth 표시하기
folium.Choropleth(
  geo_data=geo_data,
  data=df[year],
  columns=[df.index, df[year]], # 시군구
  fill_color='YlOrRd',
  threshold_scale=[10000, 100000, 300000, 500000, 700000],
  key_on='feature.properties.name' #['features'][0]['properties']['name'] 의 약속
).add_to(g_map)

g_map