In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib
import warnings
warnings.filterwarnings('ignore')

In [4]:
# 모든 컬럼 이름을 다 보여주기
pd.set_option('display.max_columns', None)

# 컬럼 하나당 표시할 최대 문자열 길이 제한 없애기
pd.set_option('display.max_colwidth', None)

# 콘솔 폭에 맞춰 자동 줄바꿈 없이 쭉 출력하기
pd.set_option('display.expand_frame_repr', False)

# 전역 출력 포맷 설정: 소수점 2자리 일반 실수 표기
pd.set_option('display.float_format', '{:.7f}'.format)

# 지수표기(sci‑notation) 사용 안 함
np.set_printoptions(suppress=True)

# 소수점 자리수 지정 (예: 소수점 이하 2자리)
np.set_printoptions(formatter={'float_kind': '{:.7f}'.format})

np.set_printoptions(threshold=np.inf)

In [ ]:
# 데이터 불러오기 
# https://data.seoul.go.kr/dataList/OA-21085/S/1/datasetView.do
hangang_month = pd.read_csv("../Data/한강공원 주차장 월별 이용 현황.csv", encoding='cp949')
hangang_month.head()

       지구별      주차장명   주차대수     이용시간       날짜
0  PLT-009  반포2,3주차장  31176  2949006  2025/08
1  PLT-011    잠실1주차장  18814   719837  2025/08
2  PLT-005    뚝섬4주차장   7919   796897  2025/08
3  PLT-004    이촌3주차장  10057   911432  2025/08
4  PLT-010  잠원2-6주차장  25096  3193104  2025/08

In [ ]:
# 데이터 불러오기 
# https://data.seoul.go.kr/dataList/OA-21086/S/1/datasetView.do
hangang_year = pd.read_csv("../Data/한강공원 주차장 연별 이용 현황.csv", encoding='cp949')
hangang_year.head()

       지구별          주차장명    주차대수      이용시간    날짜
0  PLT-005        뚝섬4주차장  149075  15271377  2025
1  PLT-010      잠원2-6주차장  423844  47784310  2025
2  PLT-002  난지1,2,3,4주차장  253108  16765707  2025
3  PLT-011        잠실1주차장  390533  16885877  2025
4  PLT-008       여의도1주차장  467690  68119425  2025

In [12]:
# 데이터 불러오기 
# https://data.seoul.go.kr/dataList/OA-21084/S/1/datasetView.do
hangang_day = pd.read_csv("../Data/한강공원 주차장 일별 이용 현황.csv", encoding='cp949')
hangang_day.head()

       지구별      주차장명  주차대수    이용시간          날짜
0  PLT-008   여의도5주차장   214   13825  2025/08/10
1  PLT-003    망원1주차장   625   68058  2025/08/10
2  PLT-007    양화1주차장   381   30597  2025/08/10
3  PLT-011  잠실2,3주차장  1296  169461  2025/08/10
4  PLT-005    뚝섬4주차장  1053  113970  2025/08/10

In [13]:
# 데이터 불러오기 
# https://data.seoul.go.kr/dataList/OA-21083/S/1/datasetView.do
parking_lot = pd.read_csv("../Data/한강공원 주차장 정보.csv", encoding='cp949')
parking_lot.head()

   지구별          주차장별   위치정보(위도)    위치정보(경도)                주소   면수  장애면수  정기면수 주중 이용시간 시작 주중 이용시간 종료 주말 이용시간 시작 주말 이용시간 종료  면제시간  기본시간  기본요금  간격시간  간격요금   전일요금  주간요금  야간요금  정기금금액         주차장 운영업체                                  업체 전화번호                운영 시작기간                운영 종료기간
0   강서        강서1주차장 37.5857090 126.8182790   서울강서구방화동61(방화동)   52     0     0      06:00      24:00      06:00      24:00    10    30  1000    10   200  10000     0     0  50000   공우이엔씨(주)_양화_강서                             02-2068-9617  2023-12-01 00:00:00.0  2025-11-30 00:00:00.0
1  광나루     광나루1,2주차장 37.5538850 127.1231600    서울강동구암사동613-11  160     0     0      06:00      24:00      06:00      24:00     0     0     0    10   200  10000     0     0  50000  공우이엔씨(주)_잠실_광나루                             02-3431-3774  2023-12-01 00:00:00.0  2025-11-30 00:00:00.0
2  광나루       광나루3주차장 37.5430780 127.1177750      서울강동구풍납동49-2  183     0     0      06:00      24:00      06:00      24:00    10    30  1000    10   200  10000     0     0  50000  공우이엔씨(주)_잠실_광나루                             02-3431-3774  2023-12-01 00:00:00.0  2025-11-30 00:00:00.0
3   난지  난지1,2,3,4주차장 37.5698219 126.8736403   서울마포구상암동487-370  618     0     0      06:00      24:00      06:00      24:00     0     0     0    10   200  10000     0     0  50000    (주)현암파킹_망원_난지  (주간) 010-2821-9227 , (야간) 070-7076-0132  2025-02-01 00:00:00.0  2027-01-31 00:00:00.0
4   뚝섬        뚝섬1주차장 37.5276908 127.0781632  서울광진구자양동409(자양동)   64     0     0      06:00      24:00      06:00      24:00    10    30  1000    10   200  10000     0     0  50000      공우이엔씨(주)_뚝섬                              02-455-7279  2024-12-01 00:00:00.0  2026-11-30 00:00:00.0

### 공원 이용 통계
월별 이용객 현황은 2024년까지
년도별 이용객 현황은 2023년까지

In [19]:
# 생활이동_행정동_2025.03_13시.csv
# 데이터 불러오기 
# https://data.seoul.go.kr/dataVisual/seoul/seoulLivingMigration.do?utm_source=chatgpt.com
people = pd.read_csv("../Data/생활이동_행정동_2025.03_13시.csv", encoding='cp949')
people.head()

     대상연월 요일  도착시간  출발 행정동 코드  도착 행정동 코드 성별  나이 이동유형  평균 이동 시간(분) 이동인구(합)
0  202503  일    13    1101053    1101053  F   0   EE            1   27.94
1  202503  일    13    1101053    1101053  F  10   EE           25   83.88
2  202503  일    13    1101053    1101053  F  10   EH           30   23.72
3  202503  일    13    1101053    1101053  F  10   HE           13    5.79
4  202503  일    13    1101053    1101053  F  15   EE           36   56.76

In [18]:
# 뚝섬제1주차장, 자양2동, 1105065
# 뚝섬제2주차장, 자양3동, 1105066
# 뚝섬제3,4주차장, 자양4동,1105067

In [20]:
# 생활이동_행정동_2025.03_13시.csv
# 데이터 불러오기 
# https://data.seoul.go.kr/dataVisual/seoul/seoulLivingMigration.do?utm_source=chatgpt.com
people = pd.read_csv("../Data/생활이동_행정동_2024.01_00시.csv", encoding='cp949')
people.head()

     대상연월 요일  도착시간  출발 행정동 코드  도착 행정동 코드 성별  나이 이동유형  평균 이동 시간(분) 이동인구(합)
0  202401  일     0    1101053    1101053  F  15   WH           54    4.04
1  202401  일     0    1101053    1101053  F  20   EH          227       *
2  202401  일     0    1101053    1101053  F  25   EE            2       *
3  202401  일     0    1101053    1101053  F  25   EH            5       *
4  202401  일     0    1101053    1101053  F  25   HH           14       *