In [4]:
options(warn=-1)
options(repr.plot.width=15, repr.plot.height=9)
Sys.setlocale(category = "LC_ALL",locale = "ko_KR.UTF-8")

[1] "ko_KR.UTF-8/ko_KR.UTF-8/ko_KR.UTF-8/C/ko_KR.UTF-8/ko_KR"

In [5]:
num1 <- 10
if(num1 >= 40){
  print('40이상 입니다.')
}else if(num1 >= 30){
  print('30이상 입니다.')
}else if(num1 >= 20){
  print('20이상 입니다.')
}else(
  print('20미만 입니다.')
)

[1] "20미만 입니다."

[1] "20미만 입니다."

In [7]:
excel <- read.csv("../Data/excel.csv")
head(excel)

  q1 q2 q3 q4 q5
1 2  4  4  2  2
2 1  2  2  2  2
3 2  3  4  3  3
4 3  5  5  3  3
5 3  2  4  4  4
6 4  3  3  4  2

In [10]:
# q1컬럼에서 data가 3보다 크거나 같으면 data의 제곱근을 구하고 그렇지 않으면 원래 data를 출력하기
excel$q6 <- ifelse(excel$q1>=3, sqrt(excel$q1), excel$q1) # 3항 연산자
head(excel)

  q1 q2 q3 q4 q5 q6
1 2  4  4  2  2  2.000000
2 1  2  2  2  2  1.000000
3 2  3  4  3  3  2.000000
4 3  5  5  3  3  1.732051
5 3  2  4  4  4  1.732051
6 4  3  3  4  2  2.000000